#!/bin/bash

rm -rf Output/$1
mkdir -p Output/$1

ls Input/$1 | while read line
do
  ./colour_graph Input/$1/$line $2 $3 > Output/$1/$line.out 2>> Output/$1/$1.summary
  ./Graph_Checker/graphchecker Input/$1/$line Output/$1/$line.out >> Output/$1/$1.summary
  if [ "$?" -eq "1" ] ; then
    break;
  fi;
done
